### ISSUE TITLE
NameError: name 'threads' is not defined

### ISSUE THREAD

**Issue by ShailNair** [KennthShang/PhaGCN_newICTV#1]
Hi,
Thanks for the great tool. 
I encountered the following error regarding multiprocessing. This error shows up even if the `--threads` parameter is not mentioned.
```
python run_Speed_up.py --contigs contigs.fa \
--len 5000 \
--threads 30

...........
using preformatted DIAMOND database ...
Traceback (most recent call last):
  File "run_Speed_up.py", line 90, in <module>
    task='megablast',perc_identity=95,num_threads=threads)
NameError: name 'threads' is not defined
```
For me, i fixed it by adding 
`task='megablast',perc_identity=95,num_threads=30`
at line 90 of `run_Speed_up.py `

**Comment by KennthShang** [comment]
Thanks for reporting the bugs, we have revised the code accordingly. The --threads parameter is now available. You can pull the latest run_Speed_up.py to update the local version.

Best,
Jiayu
